name: Build

on: [ push ]

jobs:
  build-swift:
    name: Build with swift
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Package with swift
        run: swift build

  build-xcodebuild:
    name: Build with xcodebuild
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build Package with xcodebuild
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild -scheme $scheme  -destination 'platform=iOS Simulator,name=iPhone 13'
      - name: Build Example
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild clean build -project Examples/ExampleUIKit/ExampleUIKit.xcodeproj -scheme $scheme -sdk iphoneos

  run-tests:
    name: Run tests
    needs: [ build-xcodebuild, build-swift ]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set test parameters
        run: |
          sed -i -e "s/INTEGRATION_TESTS_RTMP_URL/${INTEGRATION_TESTS_RTMP_URL}/" ./Tests/ApiVideoLiveStream/Parameters.swift
          sed -i -e "s/INTEGRATION_TESTS_RTMP_STREAM_KEY/${INTEGRATION_TESTS_RTMP_STREAM_KEY}/" ./Tests/ApiVideoLiveStream/Parameters.swift
        env:
          INTEGRATION_TESTS_API_KEY: ${{ secrets.INTEGRATION_TESTS_RTMP_URL }}
          INTEGRATION_TESTS_RTMP_STREAM_KEY: ${{ secrets.INTEGRATION_TESTS_RTMP_STREAM_KEY }}
      - name: Running tests
        run: swift test

  verify_cocoapods:
    name: Verify cocoapods podspec
    needs: run-tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Verify cocoapods
        run: pod lib lint --allow-warnings

  lint:
    name: Running swiftlint
    needs: verify_cocoapods
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Run swiftlint
        run: swiftlint
